// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBseqBHMowYT0RnkH72fEkFITAmF26XtdI',
    appId: '1:119449793685:web:6d3d0db40191a8f193179c',
    messagingSenderId: '119449793685',
    projectId: 'desap-96a0a',
    authDomain: 'desap-96a0a.firebaseapp.com',
    storageBucket: 'desap-96a0a.firebasestorage.app',
    measurementId: 'G-W3WJJM5GDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQaWD9b_GK1rYOoAOGV2b_AtzuJuunCCM',
    appId: '1:119449793685:android:795bdfcecaca21f593179c',
    messagingSenderId: '119449793685',
    projectId: 'desap-96a0a',
    storageBucket: 'desap-96a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MKvnk0SNnoftaV-Jy6HhIO7V_N8T70I',
    appId: '1:119449793685:ios:413de4eb7d4eddeb93179c',
    messagingSenderId: '119449793685',
    projectId: 'desap-96a0a',
    storageBucket: 'desap-96a0a.firebasestorage.app',
    iosBundleId: 'com.example.desapv3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1MKvnk0SNnoftaV-Jy6HhIO7V_N8T70I',
    appId: '1:119449793685:ios:413de4eb7d4eddeb93179c',
    messagingSenderId: '119449793685',
    projectId: 'desap-96a0a',
    storageBucket: 'desap-96a0a.firebasestorage.app',
    iosBundleId: 'com.example.desapv3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBseqBHMowYT0RnkH72fEkFITAmF26XtdI',
    appId: '1:119449793685:web:ea848e6410e12ccb93179c',
    messagingSenderId: '119449793685',
    projectId: 'desap-96a0a',
    authDomain: 'desap-96a0a.firebaseapp.com',
    storageBucket: 'desap-96a0a.firebasestorage.app',
    measurementId: 'G-F78FDTHTDE',
  );
}
